FROM nginx:alpine

# Copy custom NGINX config that uses port 8080
COPY nginx.conf /etc/nginx/nginx.conf
COPY devops.html /usr/share/nginx/html/index.html

# Fix permissions
USER root
RUN mkdir -p /var/cache/nginx/client_temp && \
    chgrp -R 0 /var/cache/nginx /etc/nginx /usr/share/nginx/html && \
    chmod -R g+rwX /var/cache/nginx /etc/nginx /usr/share/nginx/html

# Drop root privileges
USER 1001
